trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: CadQuery/conda-packages
      endpoint: CadQuery

jobs:
- job: Linux
  timeoutInMinutes: 360
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: conda-enable.yml@templates

  - bash: |
      conda env create -f env.yml
    displayName: 'Prepare conda environment'

  - bash: |
      source activate cpp-py-bindgen && \
      python -m bindgen -n 2 parse ocp.toml out.pkl && \
      python -m bindgen -n 2 transform ocp.toml out.pkl out_f.pkl && \
      python -m bindgen -n 2 generate ocp.toml out_f.pkl
    displayName: 'Generate'

  - bash: sudo apt-get install g++-8 mesa-common-dev
    displayName: 'Install g++8 and mesa headers'

  - bash: |
      source activate cpp-py-bindgen && \
      cd OCP && \
      cat makefile && \
      make -k && \
      python -c"import OCP"
    displayName: 'Compile'
