trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: CadQuery/conda-packages
      endpoint: CadQuery

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: conda-enable.yml@templates

  - bash: |
      conda env create -f env.yml && \
      conda activate cpp-py-bindgen
    displayName: 'Prepare conda environment'

  - bash: |
      python -m bindgen -n 1 -v parse ocp.toml out.pkl && \
      python -m bindgen -n 1 -v transform ocp.toml out.pkl out_f.pkl && \
      python -m bindgen -n 1 -v generate ocp.toml out_f.pkl
    displayName: 'Generate'

  - bash: |
      cd OCP && \
      make -j -n && \
      make test
    displayName: 'Compile'
