trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr: none

jobs:
- template: conda-build.yml
    name: Linux
- template: conda-build.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
