name = "OCP"
input_folder = "/home/adam/anaconda2/envs/cpp-py-bindgen/include/opencascade"
output_folder = "./generated_gp"

include = ["Standard_*.hxx",
           "gp_*.hxx",
           "math.hxx"]

exclude = ["Standard_Handle.hxx","math_GaussPoints.hxx"]

exceptions = ["Standard_Failure","Standard_.+Error"]


module_mapping = "lambda x: Path(x).splitpath()[-1].split('.')[0].split('_')[0]"

[Operators]

    "operator*" = ["__mul__","__rmul__"]
    "operator*=" = ["__imul__"]
    "operator/" = ["__truediv__"]
    "operator/=" = ["__itruediv__"]
    "operator+" = ["__add__"]
    "operator+=" = ["__iadd__"]
    "operator-" = ["__sub__"]
    "operator-=" = ["__isub__"]
    "operator^" = ["__pow__"]
    "operator^=" = ["__ipow__"]

[Extras]

    include_pre = "OCP_specific.inc"
    include_post = false
    
[Symbols]

    path = "symbols.dat"

[Modules]

    [Modules.gp]
    
        include_header_pre = false
        exclude_functions = [,]
        exclude_classes = [,] 
        exclude_methods = [,] 
        include_header_post = false
        template_specializations = [,]
        
    [Modules.math]
    
        include_header_pre = false
        exclude_functions = [,]
        exclude_classes = [,]
        exclude_methods = [,]
        include_header_post = false
        template_specializations = [,]
        
    [Modules.Standard]
    
        include_header_pre = false
        exclude_functions = ["HashCode"]
        exclude_classes = [,]
        exclude_methods = [,]
        include_header_post = false
        template_specializations = [,]